#ifndef NAGCPP_F06_HPP
#define NAGCPP_F06_HPP
// Copyright 2019, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 27.0.0.0
#include "f06/nagcpp_f06ra.hpp"
#include "f06/nagcpp_f06ya.hpp"
#endif
