#ifndef NAGCPP_G01_HPP
#define NAGCPP_G01_HPP
// Copyright 2023, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 29.2.0.0
#include "g01/nagcpp_g01am.hpp"
#include "g01/nagcpp_g01gb.hpp"
#endif
