#ifndef NAGCPP_G01_HPP
#define NAGCPP_G01_HPP
// Copyright 2019, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 27.0.0.0
#include "g01/nagcpp_g01am.hpp"
#include "g01/nagcpp_g01gb.hpp"
#endif
