#ifndef NAGCPP_G02_HPP
#define NAGCPP_G02_HPP
// Copyright 2024, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 30.1.0.0
#include "g02/nagcpp_g02ak.hpp"
#include "g02/nagcpp_g02ma.hpp"
#endif
