#ifndef NAGCPP_G02_HPP
#define NAGCPP_G02_HPP
// Copyright 2021, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 27.1.0.0
#include "g02/nagcpp_g02ak.hpp"
#include "g02/nagcpp_g02ma.hpp"
#endif
