#ifndef NAGCPP_E04_HPP
#define NAGCPP_E04_HPP
// Copyright 2022, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 28.5.0.0
#include "e04/nagcpp_e04fg.hpp"
#include "e04/nagcpp_e04kf.hpp"
#include "e04/nagcpp_e04mt.hpp"
#include "e04/nagcpp_e04pt.hpp"
#include "e04/nagcpp_e04ra.hpp"
#include "e04/nagcpp_e04rb.hpp"
#include "e04/nagcpp_e04re.hpp"
#include "e04/nagcpp_e04rf.hpp"
#include "e04/nagcpp_e04rg.hpp"
#include "e04/nagcpp_e04rh.hpp"
#include "e04/nagcpp_e04rj.hpp"
#include "e04/nagcpp_e04rk.hpp"
#include "e04/nagcpp_e04rl.hpp"
#include "e04/nagcpp_e04rm.hpp"
#include "e04/nagcpp_e04ry.hpp"
#include "e04/nagcpp_e04rz.hpp"
#include "e04/nagcpp_e04st.hpp"
#include "e04/nagcpp_e04uc.hpp"
#include "e04/nagcpp_e04ue.hpp"
#include "e04/nagcpp_e04wb.hpp"
#include "e04/nagcpp_e04zm.hpp"
#include "e04/nagcpp_e04zn.hpp"
#endif
