#ifndef NAGCPP_HPP
#define NAGCPP_HPP
// Copyright 2019, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 27.0.0.0
#include "nagcpp_c05.hpp"
#include "nagcpp_d01.hpp"
#include "nagcpp_e01.hpp"
#include "nagcpp_e02.hpp"
#include "nagcpp_e04.hpp"
#include "nagcpp_f01.hpp"
#include "nagcpp_f06.hpp"
#include "nagcpp_f08.hpp"
#include "nagcpp_f11.hpp"
#include "nagcpp_g01.hpp"
#include "nagcpp_g02.hpp"
#include "nagcpp_x02.hpp"
#endif
