#ifndef NAGCPP_G01_HPP
#define NAGCPP_G01_HPP
// Copyright 2021, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 27.2.1.0
#include "g01/nagcpp_g01am.hpp"
#include "g01/nagcpp_g01gb.hpp"
#endif
