#ifndef NAGCPP_D01_HPP
#define NAGCPP_D01_HPP
// Copyright 2022, Numerical Algorithms Group Ltd, Oxford, UK.
// Generated by assemble.sh
// Version 28.5.0.0
#include "d01/nagcpp_d01fb.hpp"
#include "d01/nagcpp_d01tb.hpp"
#endif
